spring:
  application:
    name: SpringData

  # database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/codingnomads?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: codingNomads
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create